; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "irg|addg" --version 6
; RUN: llc -mtriple=aarch64 -mattr=+mte -verify-machineinstrs %s -o - | FileCheck %s
; RUN: opt -strip-debug -S %s | llc -mtriple=aarch64 -mattr=+mte -verify-machineinstrs -o - | FileCheck %s

; The DBG_VALUE of %a_t must not affect which stack slot is pinned to the
; unoffset IRG result. The second RUN line removes only the debug information.
source_filename = "first-slot-debug.ll"

declare ptr @llvm.aarch64.irg.sp(i64)
declare ptr @llvm.aarch64.tagp.p0(ptr, ptr, i64 immarg)
declare void @use2(ptr, ptr)

define void @f() !dbg !4 {
; CHECK-LABEL: f:
; CHECK:    irg x1, sp
; CHECK:    addg x0, x1, #16, #1
entry:
  %a = alloca i8, align 16
  %b = alloca i8, align 16
  %base = call ptr @llvm.aarch64.irg.sp(i64 0)
  %a_t = call ptr @llvm.aarch64.tagp.p0(ptr %a, ptr %base, i64 1)
  #dbg_value(ptr %a_t, !7, !DIExpression(), !8)
  %b_t = call ptr @llvm.aarch64.tagp.p0(ptr %b, ptr %base, i64 0)
  call void @use2(ptr %a_t, ptr %b_t)
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}
!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "reduced", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "reduced.c", directory: "/")
!2 = !DISubroutineType(types: !5)
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "f", scope: !1, file: !1, line: 1, type: !2, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !6)
!5 = !{}
!6 = !{!7}
!7 = !DILocalVariable(name: "a_tagged", scope: !4, file: !1, line: 1, type: !9)
!8 = !DILocation(line: 1, column: 1, scope: !4)
!9 = !DIBasicType(name: "pointer", size: 64, encoding: DW_ATE_unsigned)
